change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
include-labels:
  - "beta"
  - "breaking-change"
  - "bug"
  - "dependencies"
  - "enhancement"
  - "refactor"
categories:
  - title: "Breaking changes"
    label: "breaking-change"

  - title: "Beta changes"
    label: "beta"
    collapse-after: 1

  - title: "New features"
    label: "enhancement"

  - title: "Refactor"
    label: "refactor"

  - title: "Bug fixes"
    label: "bug"

  - title: "Dependency updates"
    label: "dependencies"
    collapse-after: 1

template: |
  $CHANGES
